drop database OnlineFoodDelivery;
create database OnlineFoodDelivery;

use OnlineFoodDelivery;
/* CREATE TABLES IN THE DB*/
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
Fname VARCHAR(15) NOT NULL,
Mname VARCHAR(15) NOT NULL,
Lname VARCHAR(15) NOT NULL,
Email_ID VARCHAR(50) NOT NULL,
Address VARCHAR(50),
Cust_Type VARCHAR(15) CHECK(Cust_Type IN ('Regular','Premium')),
Reward_Points INTEGER DEFAULT 0,
Standard_Delivery_Charges INTEGER DEFAULT 0,
CONSTRAINT EMAIL_PK
PRIMARY KEY (Email_ID)
);

DROP TABLE IF EXISTS RESTAURANT;
CREATE TABLE RESTAURANT (
Res_ID INTEGER NOT NULL,
Name VARCHAR(50) NOT NULL,
City VARCHAR(50) NOT NULL,
Address VARCHAR(50) NOT NULL,
Work_Phone BIGINT(13) NOT NULL,
Res_Type VARCHAR(50) ,
Owner VARCHAR(50) NOT NULL,
CONSTRAINT RESID_PK
PRIMARY KEY (Res_ID)
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS (
Order_ID INTEGER NOT NULL,
Order_Summary VARCHAR(200) NOT NULL,
Order_Amount DECIMAL(10,2) NOT NULL,
Order_DateTime DateTime NOT NULL,
Res_ID INTEGER NOT NULL,
User_Email_ID VARCHAR(50) NOT NULL,
CONSTRAINT OID_PK
PRIMARY KEY (Order_ID)
);

DROP TABLE IF EXISTS PAYMENT;
CREATE TABLE PAYMENT (
P_ID INTEGER NOT NULL,
Paid_Amount DECIMAL(10,2) NOT NULL,
Payment_Type VARCHAR(50) NOT NULL,
Payment_Status VARCHAR(50) NOT NULL,
Res_ID INTEGER NOT NULL,
CONSTRAINT PID_PK
PRIMARY KEY (P_ID)
);

DROP TABLE IF EXISTS DELIVERY_MAN;
CREATE TABLE DELIVERY_MAN (
Emp_ID VARCHAR(50) NOT NULL,
Name VARCHAR(50) NOT NULL,
Work_Phone BIGINT(13) NOT NULL,
Salary DECIMAL(10,2) CHECK(Salary>0),
Res_ID INTEGER NOT NULL,
CONSTRAINT EMPID_PK
PRIMARY KEY (Emp_ID)
);


DROP TABLE IF EXISTS ORDER_PAYMENT;
CREATE TABLE ORDER_PAYMENT (
P_ID INTEGER NOT NULL,
Order_ID INTEGER NOT NULL,
User_Email_ID VARCHAR(50) NOT NULL,
CONSTRAINT OPID_PK
PRIMARY KEY (P_ID,Order_ID,User_Email_ID)
);

DROP TABLE IF EXISTS ORDER_DELIVERY;
CREATE TABLE ORDER_DELIVERY (
DM_ID VARCHAR(50) NOT NULL,
Order_ID INTEGER NOT NULL,
User_Email_ID VARCHAR(50) NOT NULL,
CONSTRAINT OPID_PK
PRIMARY KEY (DM_ID,Order_ID,User_Email_ID)
);

DROP TABLE IF EXISTS CUST_PHONE;
CREATE TABLE CUST_PHONE (
Email_ID VARCHAR(50) NOT NULL,
Phone BIGINT(13) NOT NULL,
CONSTRAINT CPHONE_PK
PRIMARY KEY (Email_ID,Phone)
);

DROP TABLE IF EXISTS FOOD;
CREATE TABLE FOOD (
Res_ID INTEGER NOT NULL,
Item_Name VARCHAR(50) NOT NULL,
CONSTRAINT CPHONE_PK
PRIMARY KEY (Res_ID,Item_Name)
);


/* ADD CONSTRAINTS TO THE TABLES*/
ALTER TABLE ORDERS
ADD CONSTRAINT EMAIL_FK
FOREIGN KEY (User_Email_ID) REFERENCES CUSTOMER(Email_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE,
ADD CONSTRAINT RESID_FK
FOREIGN KEY (Res_ID) REFERENCES RESTAURANT(Res_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE PAYMENT
ADD CONSTRAINT P_RESID_FK
FOREIGN KEY (Res_ID) REFERENCES RESTAURANT(Res_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE ORDER_PAYMENT
ADD CONSTRAINT OP_EMAIL_FK
FOREIGN KEY (User_Email_ID) REFERENCES CUSTOMER(Email_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE,
ADD CONSTRAINT OP_OID_FK
FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE,
ADD CONSTRAINT OP_PID_FK
FOREIGN KEY (P_ID) REFERENCES PAYMENT(P_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;


ALTER TABLE FOOD
ADD CONSTRAINT F_RESID_FK
FOREIGN KEY (Res_ID) REFERENCES RESTAURANT(Res_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE DELIVERY_MAN
ADD CONSTRAINT D_RESID_FK
FOREIGN KEY (Res_ID) REFERENCES RESTAURANT(Res_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE ORDER_DELIVERY
ADD CONSTRAINT OD_EMAIL_FK
FOREIGN KEY (User_Email_ID) REFERENCES CUSTOMER(Email_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE,
ADD CONSTRAINT OD_OID_FK
FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE,
ADD CONSTRAINT DM_ID_FK
FOREIGN KEY (DM_ID) REFERENCES DELIVERY_MAN(Emp_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;