
/* Set local_infile to 1 for Loading Data from local file*/
SET GLOBAL local_infile = 1;

/* Loading Data into the tables from local .dat files*/
LOAD DATA LOCAL INFILE 'D:/LaTech/DBT/Project/Part-B/customer.dat' 
REPLACE INTO TABLE CUSTOMER  
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'D:/LaTech/DBT/Project/Part-B/restaurant.dat' 
REPLACE INTO TABLE RESTAURANT 
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'D:/LaTech/DBT/Project/Part-B/orders.dat' 
REPLACE INTO TABLE ORDERS 
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'D:/LaTech/DBT/Project/Part-B/cust_phone.dat' 
REPLACE INTO TABLE CUST_PHONE 
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'D:/LaTech/DBT/Project/Part-B/payment.dat' 
REPLACE INTO TABLE PAYMENT 
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'D:/LaTech/DBT/Project/Part-B/food.dat' 
REPLACE INTO TABLE FOOD 
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'D:/LaTech/DBT/Project/Part-B/delivery_man.dat' 
REPLACE INTO TABLE DELIVERY_MAN 
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'D:/LaTech/DBT/Project/Part-B/order_payment.dat' 
REPLACE INTO TABLE ORDER_PAYMENT 
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'D:/LaTech/DBT/Project/Part-B/order_delivery.dat' 
REPLACE INTO TABLE ORDER_DELIVERY 
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

